# Generated by Django 4.2 on 2023-05-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_delete_listing_band_active_band_biography_band_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='band',
            name='genre',
            field=models.CharField(choices=[('HH', 'Hip Hop'), ('SP', 'Synth Pop'), ('AR', 'Alternative Rock'), ('CR', 'Chretiens')], max_length=5),
        ),
    ]
