# Generated by Django 4.2 on 2023-05-11 14:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_alter_band_genre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=1000)),
                ('sold', models.BooleanField(default=False)),
                ('year_listing', models.IntegerField(validators=[django.core.validators.MinValueValidator(2022), django.core.validators.MaxValueValidator(2023)])),
            ],
        ),
    ]
